# Generated by Django 5.1.6 on 2025-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_appointment_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='Not specified'),
        ),
    ]
