# Generated by Django 5.2 on 2025-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
