# Generated by Django 5.2 on 2025-06-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_appointment_has_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='has_conversation',
        ),
    ]
