# Generated by Django 5.1.6 on 2025-03-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_replacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='replaced_appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.appointment'),
            preserve_default=False,
        ),
    ]
