# Generated by Django 5.1.6 on 2025-03-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_replacementrequest_replaced_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplacementRequest',
        ),
    ]
