# Generated by Django 5.1.6 on 2025-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_delete_replacementrequest'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_patient_appointment',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('doctor', 'date', 'time'), name='unique_doctor_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('patient', 'date', 'time'), name='unique_patient_appointment'),
        ),
    ]
