# Generated by Django 5.1.6 on 2025-03-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_appointment_unique_doctor_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='replaces_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement', to='agenda.appointment'),
        ),
    ]
