# Generated by Django 5.1.6 on 2025-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_appointment_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Very Low')], default=5),
        ),
    ]
