# Generated by Django 5.2 on 2025-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='dialogue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='processed_dialogue',
            field=models.TextField(blank=True),
        ),
    ]
