# Generated by Django 5.2 on 2025-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0002_remove_conversation_message_conversation_dialogue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='dialogue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='processed_dialogue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
